/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  bio?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: PostReference;
  language?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  excerpt?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  language?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Category
  | Slug
  | SanityImageAssetReference
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | TranslationMetadata
  | InternationalizedArrayReference
  | PostReference
  | InternationalizedArrayReferenceValue
  | CategoryReference
  | Post
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/app/sitemap.ts
// Variable: sitemapPostsQuery
// Query: *[_type == "post" && defined(slug.current)] {  "slug": slug.current,  _updatedAt}
export type SitemapPostsQueryResult = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Source: src/features/blog/queries/get-post.ts
// Variable: GET_POST_QUERY
// Query: coalesce(    *[_type == "post" && slug.current == $slug && language == $locale][0] {  _id, title, "slug": slug.current, publishedAt, excerpt, body,  mainImage, "categories": categories[]->{title, "slug": slug.current},  "estimatedReadingTime": round(length(pt::text(body)) / 5 / 200) + 1},    *[_type == "post" && slug.current == $slug && language == "en"][0] {  _id, title, "slug": slug.current, publishedAt, excerpt, body,  mainImage, "categories": categories[]->{title, "slug": slug.current},  "estimatedReadingTime": round(length(pt::text(body)) / 5 / 200) + 1},    *[_type == "post" && slug.current == $slug && !defined(language)][0] {  _id, title, "slug": slug.current, publishedAt, excerpt, body,  mainImage, "categories": categories[]->{title, "slug": slug.current},  "estimatedReadingTime": round(length(pt::text(body)) / 5 / 200) + 1}  )
export type GET_POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  estimatedReadingTime: number;
} | null;

// Source: src/features/blog/queries/get-post.ts
// Variable: GET_POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current) && (language == "en" || !defined(language))]{"slug": slug.current}
export type GET_POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/features/blog/queries/get-posts.ts
// Variable: GET_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current) && (    language == $locale ||    (!defined(language) && count(*[_type == "post" && slug.current == ^.slug.current && language == $locale]) == 0)  )] | order(publishedAt desc) {    _id, title, "slug": slug.current, publishedAt, excerpt, language,    mainImage,    "estimatedReadingTime": round(length(pt::text(body)) / 5 / 200) + 1,    "categories": categories[]->{title, "slug": slug.current}  }
export type GET_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  language: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  estimatedReadingTime: number;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Source: src/features/home/queries/get-featured-posts.ts
// Variable: GET_FEATURED_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc) [0...3] {    _id, title, "slug": slug.current, publishedAt, excerpt,    mainImage,    "estimatedReadingTime": round(length(pt::text(body)) / 5 / 200) + 1,    "categories": categories[]->{title, "slug": slug.current}  }
export type GET_FEATURED_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  estimatedReadingTime: number;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "post" && defined(slug.current)] {\n  "slug": slug.current,\n  _updatedAt\n}': SitemapPostsQueryResult;
    '\n  coalesce(\n    *[_type == "post" && slug.current == $slug && language == $locale][0] {\n  _id, title, "slug": slug.current, publishedAt, excerpt, body,\n  mainImage, "categories": categories[]->{title, "slug": slug.current},\n  "estimatedReadingTime": round(length(pt::text(body)) / 5 / 200) + 1\n},\n    *[_type == "post" && slug.current == $slug && language == "en"][0] {\n  _id, title, "slug": slug.current, publishedAt, excerpt, body,\n  mainImage, "categories": categories[]->{title, "slug": slug.current},\n  "estimatedReadingTime": round(length(pt::text(body)) / 5 / 200) + 1\n},\n    *[_type == "post" && slug.current == $slug && !defined(language)][0] {\n  _id, title, "slug": slug.current, publishedAt, excerpt, body,\n  mainImage, "categories": categories[]->{title, "slug": slug.current},\n  "estimatedReadingTime": round(length(pt::text(body)) / 5 / 200) + 1\n}\n  )\n': GET_POST_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current) && (language == "en" || !defined(language))]{"slug": slug.current}': GET_POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current) && (\n    language == $locale ||\n    (!defined(language) && count(*[_type == "post" && slug.current == ^.slug.current && language == $locale]) == 0)\n  )] | order(publishedAt desc) {\n    _id, title, "slug": slug.current, publishedAt, excerpt, language,\n    mainImage,\n    "estimatedReadingTime": round(length(pt::text(body)) / 5 / 200) + 1,\n    "categories": categories[]->{title, "slug": slug.current}\n  }\n': GET_POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc) [0...3] {\n    _id, title, "slug": slug.current, publishedAt, excerpt,\n    mainImage,\n    "estimatedReadingTime": round(length(pt::text(body)) / 5 / 200) + 1,\n    "categories": categories[]->{title, "slug": slug.current}\n  }\n': GET_FEATURED_POSTS_QUERY_RESULT;
  }
}
